accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView


from accounts import views
app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    
]

core/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from core import views

app_name = 'core'

urlpatterns = [
    path('shortenUrl', csrf_exempt(views.createShortenedUrl), name='new_url'),
    path('allUrls', csrf_exempt(views.getAllUrls), name='get_all_urls'),
    path('editUrl/<int:pk>', csrf_exempt(views.editShortenedUrl), name='edit_url'),
    path('deleteUrl/<int:pk>', csrf_exempt(views.deleteShortenedUrl), name='delete_url'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

url_shortener/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from core.views import redirectToUrl
from accounts.views import dashboard


urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include('core.urls')),
    path('<str:shortened_url>', redirectToUrl, name='redirect_url'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

def default_expiry_time():
    return timezone.now() + timedelta(days=365)

class StoredUrls(models.Model):
    shortened_url = models.CharField(max_length=10, null=True, blank=True)
    redirect_url = models.URLField()
    creation_time = models.DateTimeField(auto_now_add=True, editable=False)
    expiry_time = models.DateTimeField(
        default=default_expiry_time)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    visits = models.PositiveIntegerField(default=0)

    def increment_visits(self):
        self.visits = self.visits + 1
        self.save()

    def expiry_time_days(self):
        return (self.expiry_time - self.creation_time).days

    class Meta:
        verbose_name = 'Stored URL'
        verbose_name_plural = 'Stored URLs'

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from core.models import StoredUrls


def register(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
    context['form'] = form
    return render(request, 'accounts/register.html', context)


@login_required
def dashboard(request):
    urls = StoredUrls.objects.filter(user=request.user).order_by('-creation_time')
    return render(request, 'dashboard.html', context={'urls': urls})

core/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponsePermanentRedirect, Http404, HttpResponseServerError
from django.http.response import HttpResponse
from django.utils import timezone

from rest_framework.response import Response
from rest_framework import serializers, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from core.serializers import ShortenedUrlSerializer, CreateShortenedUrlSerializer
from core.models import StoredUrls
from core.response import StandardResponseStructure


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def createShortenedUrl(request) -> Response:
    r = StandardResponseStructure()
    data = CreateShortenedUrlSerializer(data=request.data)
    if data.is_valid():
        url_obj = data.save(user=request.user)
        serialized = ShortenedUrlSerializer(url_obj)
        r.status = True
        r.data.append(serialized.data)
        return Response(r.object(), status=status.HTTP_200_OK)
    r.message = data.errors
    return Response(r.object(), status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def getAllUrls(request) -> Response:
    r = StandardResponseStructure()
    urls = StoredUrls.objects.filter(user=request.user)
    serialized = ShortenedUrlSerializer(urls, many=True)
    r.status = True
    r.data = serialized.data
    return Response(r.object(), status=status.HTTP_200_OK)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def editShortenedUrl(request, pk) -> Response:
    r = StandardResponseStructure()
    try:
        instance = StoredUrls.objects.get(pk=pk)
        if not instance.user == request.user:
            raise ObjectDoesNotExist
    except ObjectDoesNotExist:
        r.message = 'URL not found or user not authorized'
        return Response(r.object(), status=status.HTTP_200_OK)
    data = CreateShortenedUrlSerializer(instance, data=request.data, partial=True)
    if data.is_valid():
        obj = data.save()
        serialized = ShortenedUrlSerializer(obj)
        r.data.append(serialized.data)
        r.status = True
        return Response(r.object(), status=status.HTTP_200_OK)
    r.message = data.errors
    return Response(r.object(), status=status.HTTP_200_OK)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def deleteShortenedUrl(request, pk) -> Response:
    r = StandardResponseStructure()
    try:
        instance = StoredUrls.objects.get(pk=pk)
        if not instance.user == request.user:
            raise ObjectDoesNotExist
    except ObjectDoesNotExist:
        r.message = 'URL not found or user not authorized'
        return Response(r.object(), status=status.HTTP_200_OK)
    instance.delete()
    r.status = True
    return Response(r.object(), status=status.HTTP_200_OK)


def redirectToUrl(request, shortened_url):
    try:
        instance = StoredUrls.objects.get(shortened_url=shortened_url)
        if instance.expiry_time < timezone.now():
            return HttpResponse("Link Expired!")
        instance.increment_visits()
        return HttpResponsePermanentRedirect(instance.redirect_url)
    except ObjectDoesNotExist:
        raise Http404
    except:
        return HttpResponseServerError("Something went wrong!")

templates/accounts/login.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title> Login </title>
        <link rel='stylesheet' href="{% static 'register.css' %}">
    </head>
    <body>
        <div class="user">
            <header class="user__header">
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3219/logo.svg" alt="" />
                <h1 class="user__title">Login Here</h1>
            </header>
            <div style='background-color:white'>
                {% for key, value in form.errors.items %}
                    <small>{{ value }}</small>
                {% endfor %}
            </div>
            <form class="form" method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form__group">
                        <label>{{ field.label }}</label>
                        {% render_field field class+='form__input' %}
                    </div>
                {% endfor %}
                <button class="btn" type="submit">Login</button>
            </form>
            <div>
                <small>Don't have an account? <a href="{% url 'accounts:register' %}">Register</a></small>
            </div>
        </div>

        <script src="{% static 'register.js' %}"></script>
    </body>
</html>

templates/accounts/register.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <title> Register </title>
        <link rel='stylesheet' href="{% static 'register.css' %}">
    </head>
    <body>
        <div class="user">
            <header class="user__header">
                <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3219/logo.svg" alt="" />
                <h1 class="user__title">Register Here</h1>
            </header>
            <div style='background-color:white'>
                {% for key, value in form.errors.items %}
                    <small>{{ value }}</small>
                {% endfor %}
            </div>
            <form class="form" method='POST'>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form__group">
                        <label>{{ field.label }}</label>
                        {% render_field field class+='form__input' %}
                    </div>
                {% endfor %}
                <button class="btn" type="submit">Register</button>
            </form>
            <div>
                <small>Already have an account? <a href="{% url 'accounts:login' %}">Login</a></small>
            </div>
        </div>

        <script src="{% static 'register.js' %}"></script>
    </body>
</html>

templates/dashboard.html
{% load static humanize %}
<!Doctype html>
<html>
    <head>
        <title>Dashboard</title>
        <link rel='stylesheet' href="{% static 'bootstrap.min.css' %}">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">MiniatureURLs</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item active mt-2 mr-2">
                    <h5>{{ request.user.username }}</h5>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                </ul>
            </div>
        </nav>

        <div class='container'>
            <div class='row justify-content-center mt-4'>
                <div id='shorten-url-form' class='mb-4 form-group'>
                    <form method='POST' id='short-url-form' action="{% url 'core:new_url' %}">
                        <div class='row align-items-right mb-4'>
                            <div class='col-sm-4'>
                                <label for='r'>URL</label>
                                <input type='text' class='form-control' id='r' name='redirect_url' placeholder='Link to shorten'>
                            </div>
                            <div class='col-sm-4'>
                                <label for='ex'>Validity(in days)</label>
                                <input type='number' class='form-control' id='ex' name='expiry_time' placeholder='Link Validity in days' value=365>
                            </div>
                            <div class='col-sm-4 mt-4'>
                                <button type='button' id='submit-button' class='btn btn-success'>Shorten Me!</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="container-fluid">
                <table class="table table-striped table-bordered table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Creation Time</th>
                            <th scope="col">Tiny URL</th>
                            <th scope="col">Redirect URL</th>
                            <th scope="col">Visits</th>
                            <th scope="col">Expiry Time</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody id='urls-data'>
                        {% for url in urls %}
                            <tr>
                                <td scope="row">{{ url.creation_time|naturaltime }}</td>
                                <td>
                                    <a href="https://miniatureurls.ml/{{ url.shortened_url }}">
                                        miniatureurls.ml/{{ url.shortened_url }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ url.redirect_url }}">
                                        {{ url.redirect_url|truncatechars:30 }}
                                    </a>
                                </td>
                                <td>{{ url.visits }}</td>
                                <td>{{ url.expiry_time|naturaltime }}</td>
                                <td>
                                    <div class='col-sm-2'>
                                        <button 
                                            data-id='{{ url.pk }}' type='button'
                                            data-url='{{ url.redirect_url }}'
                                            data-expiry='{{ url.expiry_time_days }}'
                                            class='edit-button btn btn-primary mb-2' 
                                            data-toggle="modal" data-target="#edit-modal"
                                        >
                                            Edit
                                        </button>
                                    </div>
                                    <div class='col-sm-2'>
                                        <button 
                                            data-id='{{ url.pk }}' type='button' 
                                            class='delete-button btn btn-danger '
                                        >
                                            Delete
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="modal" id='edit-modal' tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit URL</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method='POST' id='edit-url-form'>
                        <label for='redirect_url_edit'>URL</label>
                        <input type='text' class='form-control' id='redirect_url_edit' name='redirect_url'>
                        <label for='expiry_time_edit'>Validity(in days)</label>
                        <input type='number' class='form-control' id='expiry_time_edit' name='expiry_time'>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id='edit-form-btn' class="btn btn-primary">Save changes</button>
                </div>
                </div>
            </div>
        </div>

        <script src="{% static 'jquery.js' %}"></script>
        <script src="{% static 'popper.js' %}"></script>
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('.edit-button').click(function(e) {
            var expiry = $(this).data('expiry')
            var pk = $(this).data('id')
            var redirect_url = $(this).data('url')
            console.log(expiry, pk, redirect_url)
            $('#redirect_url_edit').val(redirect_url)
            $('#edit-form-btn').attr('data-id', pk)
            $('#expiry_time_edit').val(expiry)
        })

        $('#submit-button').click(function(e) {
            e.stopImmediatePropagation();
            var csrftoken = getCookie('csrftoken');
            console.log(csrftoken);
            $.ajax({
                url: "{% url 'core:new_url' %}",
                headers: {'X-CSRFToken': csrftoken},
                method: 'POST',
                data: $('#short-url-form').serialize(),
                success: function (data, status, xhr) {
                    console.log(data['data'][0]);
                    console.log(status);
                    var resStatus = data['status'];
                    if (resStatus) {
                        location.reload()
                    }
                    else {
                        var message = data['message']
                        console.log(data)
                        var error = ''
                        Object.keys(message).forEach(function(key) {
                            error += message[key] + '\n'
                        });
                        alert(error)
                    }
                },
                error: function(data, status, xhr) {
                    console.log(status)
                }
            });
        });

        $('#edit-form-btn').click(function(e) {
            e.preventDefault();
            var csrftoken = getCookie('csrftoken');
            console.log(csrftoken);
            $.ajax({
                url: `api/editUrl/${$(this).data('id')}`,
                headers: {'X-CSRFToken': csrftoken},
                method: 'POST',
                data: $('#edit-url-form').serialize(),
                success: function (data, status, xhr) {
                    var resStatus = data['status'];
                    if (resStatus) {
                        location.reload();
                    } else {
                        var message = data['message']
                        var error = ''
                        Object.keys(message).forEach(function(key) {
                            error += message[key] + '\n'
                        });
                        alert(error)
                    }
                },
                error: function(data, status, xhr) {
                    console.log(status)
                }
            });
        });

        $('.delete-button').click(function(e) {
            e.stopImmediatePropagation();
            var csrftoken = getCookie('csrftoken');
            console.log(csrftoken);
            $.ajax({
                url: `api/deleteUrl/${$(this).data('id')}`,
                headers: {'X-CSRFToken': csrftoken},
                method: 'POST',
                success: function (data, status, xhr) {
                    var resStatus = data['status'];
                    if (resStatus) {
                        location.reload();
                    } else {
                        var message = data['message']
                        var error = ''
                        Object.keys(message).forEach(function(key) {
                            error += message[key] + '\n'
                        });
                        alert(error)
                    }
                },
                error: function(data, status, xhr) {
                    console.log(status)
                }
            });
        });
        </script>

    </body>

</html>